#!/usr/bin/python

import sys, os
import subprocess


# set variable
VOLUME = 'volume'
FOLDER = '.t0yboX'
TOYBOX = 't0yboX'
TOYBOX_PATH = os.path.expanduser('~') + '/' + FOLDER

if len(sys.argv) > 1:
    # copy or move file
    if sys.argv[1]  == '-m' and len(sys.argv) > 2:
        file_index = 2
        cmd = 'sudo mv {0} {1}/{2}'
    else:
        file_index = 1
        cmd = 'sudo cp -r {0} {1}/{2}'

    cmd = cmd.format(sys.argv[file_index], TOYBOX_PATH, VOLUME)
    os.system(cmd)

# RUN CTF DOCKER TOOL!!! 
os.chdir(TOYBOX_PATH)
os.system('sudo docker-compose run t0yboX bash')